name: instagram_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.4.1
  firebase_storage: ^11.0.14
  firebase_auth: ^4.2.9
  firebase_auth_web: ^5.2.3
  cloud_firestore: ^4.4.3
  flutter_svg: ^2.0.2
  image_picker: ^0.8.6+4
  provider: ^6.0.5
  uuid: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - images/

